name: zoning.space
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0
- backports.functools_lru_cache=1.4
- blas=1.1
- bzip2=1.0.6
- ca-certificates=2017.11.5
- cairo=1.14.10
- certifi=2017.11.5
- clangdev=5.0.0
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- curl=7.55.1
- cycler=0.10.0
- descartes=1.1.0
- expat=2.2.5
- fontconfig=2.12.6
- freetype=2.8.1
- freexl=1.0.4
- gdal=2.2.3
- geopandas=0.3.0
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.55.0
- hdf4=4.2.13
- hdf5=1.10.1
- icu=58.2
- jpeg=9b
- json-c=0.12.1
- kealib=1.4.7
- krb5=1.14.2
- libcxx=5.0.0
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.2.3
- libgfortran
- libiconv=1.15
- libkml=1.3.0
- libnetcdf
- libpng=1.6.34
- libpq=9.6.3
- libspatialindex=1.8.5
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.9
- libxml2=2.9.7
- llvmdev=5.0.0
- matplotlib=2.1.2
- munch=2.2.0
- ncurses=5.9
- numpy=1.14.0
- openblas=0.2.20
- openjpeg=2.3.0
- openssl=1.0.2n
- pandas=0.22.0
- pcre=8.39
- pip=9.0.1
- pixman=0.34.0
- poppler=0.61.1
- poppler-data=0.4.8
- proj4=4.9.3
- psycopg2=2.7.3.2
- pyparsing=2.2.0
- pysal=1.14.3
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- readline=7.0
- rtree=0.8.3
- scipy=1.0.0
- setuptools=38.4.0
- shapely=1.6.3
- six=1.11.0
- sqlalchemy=1.1.13
- sqlite=3.20.1
- tk=8.6.7
- tornado=4.5.3
- wheel=0.30.0
- xerces-c=3.2.0
- xz=5.2.3
- zlib=1.2.11
- appnope=0.1.0
- decorator=4.2.1
- fiona=1.7.10
- ipykernel=4.8.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- jedi=0.11.1
- jupyter_client=5.2.1
- jupyter_core=4.4.0
- libsodium=1.0.15
- parso=0.1.1
- pexpect=4.3.1
- pickleshare=0.7.4
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- pygments=2.2.0
- pyproj=1.9.5.1
- pyzmq=16.0.3
- simplegeneric=0.8.1
- traitlets=4.3.2
- wcwidth=0.1.7
- zeromq=4.2.2
- tqdm=4.19.5
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils
  - jupyter-client==5.2.1
  - jupyter-core
  - prompt-toolkit==1.0.15
  - urwid==2.0.1
  - partridge
